import sys
import re
from typing import List, Dict, Any


def to_camel_case(text: str) -> str:
    """
    Convert a space-separated string to camelCase format.

    Parameters
    ----------
    text : str
        The input string to be converted.

    Returns
    -------
    str
        The camelCased version of the input string, with special characters removed.

    Examples
    --------
    >>> to_camel_case("HEIGHT OF SENSOR ABOVE LOCAL GROUND")
    'heightOfSensorAboveLocalGround'
    """
    s = re.sub(r"[^a-zA-Z0-9\s]", "", text)
    words = s.split()
    if not words:
        return ""
    return words[0].lower() + "".join(w.capitalize() for w in words[1:])


def parse_queries(filename: str) -> List[Dict[str, str]]:
    """
    Parse a show_queries.x output file into a structured dictionary.

    Parameters
    ----------
    filename : str
        The path to the text file generated by show_queries.x.

    Returns
    -------
    List[Dict[str, str]]
        A list of parsed query definitions, each containing dimensions,
        data types, BUFR queries, descriptions, and root mnemonics.

    Examples
    --------
    >>> parse_queries("test/query.example.txt")
    [{'dim': '1d', 'type': 'float', 'query': '*/TMDB', 'desc': 'TEMPERATURE...', ...}]
    """
    queries = []
    with open(filename, "r") as f:
        lines = f.readlines()

    start_parsing = False
    for line in lines:
        if line.strip() == "Queries:":
            start_parsing = True
            continue
        if start_parsing:
            if not line.strip():
                continue
            parts = line.strip().split(None, 3)
            if len(parts) >= 3:
                dim = parts[0]
                typ = parts[1]
                query = parts[2]
                desc = parts[3].strip() if len(parts) > 3 else query.split("/")[-1]

                # Replace root node with '*'
                query_parts = query.split("/", 1)
                if len(query_parts) > 1:
                    query_path = "*/" + query_parts[1]
                else:
                    query_path = query
                queries.append({
                    "dim": dim,
                    "type": typ,
                    "query": query_path,
                    "desc": desc,
                    "mnemonic": query.split("/")[-1].split("[")[0]
                })
    return queries


def generate_yaml(queries: List[Dict[str, str]], outfile: str) -> None:
    """
    Generate an IODA-compliant BUFR configuration YAML file.

    Parameters
    ----------
    queries : List[Dict[str, str]]
        A list of parsed BUFR queries containing variable definitions.
    outfile : str
        The destination file path for the generated YAML.

    Returns
    -------
    None
        Writes the structured configuration directly to the filesystem.

    Examples
    --------
    >>> generate_yaml(queries, "output_mapping.yaml")
    """
    # Determine timestamp components
    time_mnemonics = ["YEAR", "MNTH", "DAYS", "HOUR", "MINU"]
    time_queries = {q["mnemonic"]: q["query"] for q in queries}
    has_time = all(k in time_queries for k in time_mnemonics)
    
    receipt_mnemonics = ["RCYR", "RCMO", "RCDY", "RCHR", "RCMI"]
    has_receipt = all(k in time_queries for k in receipt_mnemonics)

    with open(outfile, "w") as f:
        f.write("# Auto-generated BUFR YAML mapping\n\n")
        f.write("bufr:\n")
        f.write("  variables:\n")
        
        # MetaData section
        f.write("    # MetaData\n")
        if has_time:
            f.write("    timestamp:\n")
            f.write("      datetime:\n")
            f.write(f"        year: \"{time_queries[\"YEAR\"]}\"\n")
            f.write(f"        month: \"{time_queries[\"MNTH\"]}\"\n")
            f.write(f"        day: \"{time_queries[\"DAYS\"]}\"\n")
            f.write(f"        hour: \"{time_queries[\"HOUR\"]}\"\n")
            f.write(f"        minute: \"{time_queries[\"MINU\"]}\"\n\n")

        if has_receipt:
            f.write("    dataReceiptTime:\n")
            f.write("      datetime:\n")
            f.write(f"        year: \"{time_queries[\"RCYR\"]}\"\n")
            f.write(f"        month: \"{time_queries[\"RCMO\"]}\"\n")
            f.write(f"        day: \"{time_queries[\"RCDY\"]}\"\n")
            f.write(f"        hour: \"{time_queries[\"RCHR\"]}\"\n")
            f.write(f"        minute: \"{time_queries[\"RCMI\"]}\"\n\n")

        seen_names = {}
        meta_mnemonics = ["CLATH", "CLONH", "CLAT", "CLON", "HSMSL", "HBMSL", "STSN", "WMOB", "WMOS", "RPID"]
        
        obs_vars = []
        meta_vars = []
        
        for q in queries:
            mnemonic = q["mnemonic"]
            if has_time and mnemonic in time_mnemonics:
                continue
            if has_receipt and mnemonic in receipt_mnemonics:
                continue
                
            base_name = to_camel_case(q["desc"])
            if not base_name:
                base_name = mnemonic.lower()
                
            # clean up name to handle uniqueness without being too long
            # check if it contains array index
            array_idx = ""
            if "[" in q["query"] and "]" in q["query"]:
                array_idx = "_" + q["query"].split("[")[1].split("]")[0]
                
            var_name = base_name + array_idx
            
            if var_name in seen_names:
                seen_names[var_name] += 1
                var_name = f"{var_name}_{mnemonic}_{seen_names[var_name]}"
            else:
                seen_names[var_name] = 1
                
            is_meta = mnemonic in meta_mnemonics
            
            var_text = f"    {var_name}:\n"
            var_text += f"      query: \"{q['query']}\"\n"
            if q['type'] == 'float':
                var_text += f"      type: float\n"
            if q['type'] == 'string':
                var_text += f"      type: string\n"
            var_text += "\n"
            
            if is_meta:
                meta_vars.append((var_name, q, var_text))
            else:
                obs_vars.append((var_name, q, var_text))
                
        for _, _, text in meta_vars:
            f.write(text)
            
        f.write("    # ObsValue\n")
        for _, _, text in obs_vars:
            f.write(text)
            
        f.write("encoder:\n")
        f.write("  variables:\n\n")
        f.write("    # MetaData\n")
        
        if has_time:
            f.write("    - name: \"MetaData/dateTime\"\n")
            f.write("      coordinates: \"longitude latitude\"\n")
            f.write("      source: variables/timestamp\n")
            f.write("      longName: \"Datetime\"\n")
            f.write("      units: \"seconds since 1970-01-01T00:00:00Z\"\n\n")
            
        if has_receipt:
            f.write("    - name: \"MetaData/dataReceiptTime\"\n")
            f.write("      source: variables/dataReceiptTime\n")
            f.write("      longName: \"Observation Receipt Time\"\n")
            f.write("      units: \"seconds since 1970-01-01T00:00:00Z\"\n\n")
            
        for var_name, q, _ in meta_vars:
            f.write(f"    - name: \"MetaData/{var_name}\"\n")
            f.write(f"      source: variables/{var_name}\n")
            f.write(f"      longName: \"{q['desc']}\"\n")
            if 'CLAT' in q['mnemonic']:
                f.write("      units: \"degree_north\"\n")
                f.write("      range: [-90, 90]\n")
            elif 'CLON' in q['mnemonic']:
                f.write("      units: \"degree_east\"\n")
                f.write("      range: [-180, 180]\n")
            else:
                f.write("      units: \"\"\n")
            f.write("\n")
            
        f.write("    # ObsValue\n")
        for var_name, q, _ in obs_vars:
            f.write(f"    - name: \"ObsValue/{var_name}\"\n")
            f.write("      coordinates: \"longitude latitude\"\n")
            f.write(f"      source: variables/{var_name}\n")
            f.write(f"      longName: \"{q['desc']}\"\n")
            f.write("      units: \"\"\n")
            f.write("\n")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python queries_to_yaml.py <show_queries_output.txt> [output.yaml]")
        sys.exit(1)
        
    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "output.yaml"
    
    queries = parse_queries(input_file)
    generate_yaml(queries, output_file)
    print(f"Generated {output_file}\n")