
root_dir: "/scratch4/NAGAPE/gpu-ai4wp/Ronald.McLaren/geode"
debug: true

database:
  type: sqlite
  db_path: "geode.db"

  # type: postgres
  # host: "localhost"
  # port: 5432
  # database: "geode"
  # user: "geode_user"
  # password: "geode_password"

data_lake:
  dir: "lake"
  format: "netcdf"
  split_by: "day"  # Options: "year", "month", "day"
  filename_template: "{name}_{year}{month}{day}.nc"  # Template for output filenames

wis2:
  broker_address: "wis2node.globaldata.nws.noaa.gov"
  broker_port: 443
  use_websockets: true
  topic: "origin/a/wis2/us-noaa-nws/data/core/weather/#"
  download_dir: "downloads"

bufr:
  table_path: "/scratch3/NCEPDEV/da/Ronald.McLaren/installs/tables"
