
root_dir: ""
run_for_num_sec: 180

data_lake:
  type : "icechunk"
  base_dir: "lake"

wis2:
  broker_address: "wis2node.globaldata.nws.noaa.gov"
  broker_port: 443
  use_websockets: true
  topic: "origin/a/wis2/us-noaa-nws/data/core/weather/#"
  download_dir: "downloads"

ncep_dump:
  root_path: ""

bufr: null
