name: Run Pytests

on:
  pull_request:
  schedule:
    # Run daily at 11:30 UTC to verify tests still work as expected
    - cron: '30 11 * * *'

jobs:
  test-data:
    name: Run GEODE Pytests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/noaa-emc/geode:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user 0

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Install GEODE from source
        run: |
          pip install ./

      - name: Run tests
        run: |
          python -m pytest test/ -v -s -W error::pytest.PytestUnhandledThreadExceptionWarning
  